//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresses
    {
        public Adresses()
        {
            this.Utilisateurs = new HashSet<Utilisateurs>();
        }
    
        public int IdAdresse { get; set; }
        public string Ligne1 { get; set; }
        public string Ligne2 { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
    
        public virtual ICollection<Utilisateurs> Utilisateurs { get; set; }
    }
}
