//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identites
    {
        public int IdIdentite { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Identifiant { get; set; }
        public string IdUser { get; set; }
    
        public virtual Administrateurs Administrateurs { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
