//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int IdUtilisateur { get; set; }
        public int IdAdresse { get; set; }
        public System.DateTime DateInscription { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
    
        public virtual Acheteurs Acheteurs { get; set; }
        public virtual Adresses Adresses { get; set; }
        public virtual Identites Identites { get; set; }
        public virtual NewsletterInscrits NewsletterInscrits { get; set; }
        public virtual Vendeurs Vendeurs { get; set; }
    }
}
